# Helm v3 has removed the install-crds hook so CRDs are now populated by files in the crds directory. Users of Helm v3 should set the installCRDs value to false to avoid warnings about nonexistent webhooks.
installCRDs: false

server:
  config:
    url: http://argocd.example.net
    # see: https://argoproj.github.io/argo-cd/operator-manual/user-management/#1-register-the-application-in-the-identity-provider
    dex.config: |
      connectors:
      - type: github
        id: github
        name: GitHub
        redirectURI: http://argocd.example.net/dex/callback
        config:
          clientID: Your clientID.
          clientSecret: Your clientSecret.
          orgs:
          - name: mugioka-org

  rbacConfig:
    policy.default: role:readonly

    # The Custom RBAC Configuration Example.
    # policy.csv: |
    #   p, role:org-admin, applications, *, nginx/*, allow
    #   p, role:org-admin, clusters, get, *, allow
    #   p, role:org-admin, repositories, get, *, allow
    #   p, role:org-admin, repositories, create, *, allow
    #   p, role:org-admin, repositories, update, *, allow
    #   p, role:org-admin, repositories, delete, *, allow

    #   g, mugioka-org:example, role:org-admin

  additionalProjects:
  - name: weseek-techconf
    namespace: argocd
    description: Project WESEEK techconf.
    sourceRepos:
    - 'https://github.com/MugiOka/techconf-argocd.git'
    clusterResourceWhitelist:
    - group: '*'
      kind: '*'
    destinations:
    - namespace: nginx
      server: https://kubernetes.default.svc

  additionalApplications:
  - name: nginx-with-plain-manifests
    namespace: argocd
    project: weseek-techconf
    source:
      repoURL: https://github.com/MugiOka/techconf-argocd.git
      targetRevision: master
      path: nginx-with-plain-manifests
    destination:
      server: https://kubernetes.default.svc
      namespace: nginx
    syncPolicy:
      automated:
        prune: true

  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    hosts:
    - argocd.example.net
  extraArgs:
  # To disable TLS termination and HTTPS redirection in ArgoCD
  - --insecure
