repoServer:
  volumes:
  - name: custom-tools
    emptyDir: {}
  volumeMounts:
  - name: custom-tools
    mountPath: /usr/local/bin/helmfile
    subPath: helmfile
  initContainers:
  - name: download-tools
    image: alpine:3.8
    command: [sh, -c]
    args:
    - wget -qO /custom-tools/helmfile https://github.com/roboll/helmfile/releases/download/v0.135.0/helmfile_linux_amd64;
      chmod +x /custom-tools/*
    volumeMounts:
    - mountPath: /custom-tools
      name: custom-tools

server:
  config:
    url:
    admin.enabled: "false"
    dex.config: |
      connectors:
      - type: gitlab
        id: gitlab
        name: GitLab
        config:
          baseURL:
          clientID:
          clientSecret:
          groups:
          - tech/lunar
    repositories: |
      - url:
        usernameSecret:
          name:
          key:
        passwordSecret:
          name:
          key:
    configManagementPlugins: |
      - name: helmfile
        generate:
          command: [sh, -c]
          args: 
          - helmfile repos;
            helmfile template --skip-deps

  rbacConfig:
    policy.default: role:default
    policy.csv: |
      p, role:default, accounts, get, *, allow

  additionalProjects:
  - name: sample
    namespace: argocd
    description: Project sample.
    sourceRepos:
    - '*'
    clusterResourceWhitelist:
    - group: '*'
      kind: '*'
    destinations:
    - namespace: default
      server: https://kubernetes.default.svc

  additionalApplications:
  - name: nginx-with-plain-yaml
    namespace: argocd
    project: sample
    source:
      repoURL:
      targetRevision: master
      path:
      directory:
        recurse: true
    destination:
      server: https://kubernetes.default.svc
      namespace: lunar
    syncPolicy:
      automated:
        prune: true

  ingress:
    enabled: false
