# Helm v3 has removed the install-crds hook so CRDs are now populated by files in the crds directory. Users of Helm v3 should set the installCRDs value to false to avoid warnings about nonexistent webhooks.
installCRDs: false

server:
  config:
    admin.enabled: "false"
    dex.config: |
      connectors:
      - type: gitlab
        id: gitlab
        name: GitLab
        config:
          baseURL:
          clientID:
          clientSecret:
          groups:
          -

  rbacConfig:
    policy.default: role:default
    policy.csv: |
      p, role:default, accounts, get, *, allow

  additionalProjects:
  - name: sample
    namespace: argocd
    description: Project sample.
    sourceRepos:
    - '*'
    clusterResourceWhitelist:
    - group: '*'
      kind: '*'
    destinations:
    - namespace: default
      server: https://kubernetes.default.svc

  additionalApplications:
  - name: nginx-with-plain-yaml
    namespace: argocd
    project: sample
    source:
      repoURL:
      targetRevision: master
      path:
      directory:
        recurse: true
    destination:
      server: https://kubernetes.default.svc
      namespace:
    syncPolicy:
      automated:
        prune: true

  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    hosts:
    - argocd.example.net
  extraArgs:
  # To disable TLS termination and HTTPS redirection in ArgoCD
  - --insecure
